#name: Docker Hub Description
#
#on:
#  push:
#    branches: [ main ]
#    paths:
#      - README.md
#      - .github/workflows/dockerhub-description.yml
#
#permissions:
#  contents: read
#
#jobs:
#  dockerhub-description:
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v4
#
#      - name: Update Docker Hub Description
#        uses: peter-evans/dockerhub-description@v5
#        with:
#          username: ${{ secrets.DOCKERHUB_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_TOKEN }}
#          repository: YOUR_DOCKERHUB_USERNAME/docker-atmons
#          short-description: "All the Mons Minecraft Server Docker image for Unraid (Java 21)."
#          enable-url-completion: true