#name: Docker Hub Image Deploy
#
#on:
#  push:
#    branches: ["main", "develop"]
#
#jobs:
#  docker-image:
#    runs-on: ubuntu-latest
#
#    permissions:
#      contents: read
#
#    steps:
#      - name: Check out the repository
#        uses: actions/checkout@v4
#
#      - name: Set image version manually
#        run: echo "IMAGE_VERSION=0.10.0-beta" >> $GITHUB_ENV
#
#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v3
#
#      - name: Log in to Docker Hub
#        uses: docker/login-action@v3
#        with:
#          username: ${{ secrets.DOCKERHUB_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_TOKEN }}
#
#      - name: Build and push versioned image
#        uses: docker/build-push-action@v6
#        with:
#          context: .
#          push: true
#          tags: ${{ secrets.DOCKERHUB_USERNAME }}/docker-atmons:${{ env.IMAGE_VERSION }}
#          cache-from: type=gha
#          cache-to: type=gha,mode=max
#
#      - name: Build and push latest image
#        if: github.ref_name == 'main'
#        uses: docker/build-push-action@v6
#        with:
#          context: .
#          push: true
#          tags: ${{ secrets.DOCKERHUB_USERNAME }}/docker-atmons:latest
#          cache-from: type=gha
#          cache-to: type=gha,mode=max